# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06a4b80c59dae7a58b9fa69506e22e265700ea97e738f9edf60a08ed6f1ea2d4bec43b575f2ccd7f39f3b34343175e3999769ae435cc59827e83ce6fd6a896a

test:
  secret_key_base: 18fbb953444ec8456b784f81440d17c12f9a2cfc5918e5450a77dd0eeb379eac63e66d646ae093e076f4ad6aa7821cc66109c4f16c54b68f8ae022ca74fca6bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
